before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

universal_binaries:
  - replace: true

dockers:
  - image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
      - "--build-arg=GO_PROJECT_NAME={{ .ProjectName }}"
    extra_files:
      - docker-entrypoint.sh

  - image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-arm"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-arm"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm"
      - "ghcr.io/korylprince/{{ .ProjectName }}:latest-arm"
    use: buildx
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm"
      - "--build-arg=GO_PROJECT_NAME={{ .ProjectName }}"
    extra_files:
      - docker-entrypoint.sh

  - image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:latest-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
      - "--build-arg=GO_PROJECT_NAME={{ .ProjectName }}"
    extra_files:
      - docker-entrypoint.sh

docker_manifests:
  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-arm"

  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}-arm"

  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm"

  - name_template: "ghcr.io/korylprince/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/korylprince/{{ .ProjectName }}:{{ .Tag }}-arm"
